name: Testing renders
run-name: ${{github.actor}} is testing the raytracer
on: 
    push:
        branches:
            - 'releases/**'
jobs:
    raytracerRenders:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
        with: 
            python-version: '3.12'
        - run: python test.py
        - uses: actions/upload-artifact@v4
        with:
            path: *.ppm